# Generated by Django 3.1 on 2022-03-23 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='電話')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='信箱')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立日期')),
            ],
            options={
                'verbose_name_plural': '顧客',
                'ordering': ['-phone'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '標籤',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('price', models.FloatField(null=True, verbose_name='價錢')),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True, verbose_name='類別')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='標籤')),
                ('tags', models.ManyToManyField(to='dashboard.Tag')),
            ],
            options={
                'verbose_name_plural': '商品',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='建立日期')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('OutForDelivery', 'OutForDelivery'), ('Delivered', 'Delivered')], max_length=200, null=True, verbose_name='狀態')),
                ('note', models.CharField(max_length=1000, null=True, verbose_name='備註')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer', verbose_name='顧客')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.product', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': '訂購',
                'ordering': ['-date_created'],
            },
        ),
    ]
