# Generated by Django 3.1 on 2022-03-29 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '職業名稱',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('empno', models.AutoField(primary_key=True, serialize=False, verbose_name='編號')),
                ('empname', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('Male', '男'), ('Female', '女'), ('bisexual', '雙性')], max_length=10, verbose_name='性別')),
                ('salary', models.IntegerField(verbose_name='薪資')),
                ('occupation', models.ForeignKey(blank=True, default='', help_text='職務部門', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empmodels', to='milt_sear.occupation', verbose_name='職務')),
            ],
            options={
                'verbose_name_plural': '搜尋',
                'db_table': 'emp',
                'ordering': ['-salary'],
            },
        ),
    ]
