# Generated by Django 3.1 on 2022-03-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milt_sear', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empmodel',
            options={'ordering': ['-empno'], 'verbose_name_plural': '搜尋'},
        ),
    ]
